In [1]:
import pandas as pd
import numpy as np
import warnings
from scipy.sparse import csr_matrix
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
anime_data_cleaned = pd.read_csv('csv/2020/anime_2020_cleaned.csv')
rating_data = pd.read_csv('csv/2020/rating_2020.csv')

In [57]:
# exclude anime from rating data if the id is not in anime_data_cleaned
rating_data = rating_data[rating_data['MAL_ID'].isin(anime_data_cleaned['MAL_ID'])]

In [21]:
anime_name = pd.read_csv('csv/2020/anime_2020_name.csv')

In [96]:
rating_data.shape

(57633278, 3)

In [58]:
counts = rating_data['user_id'].value_counts()
rating_data = rating_data[rating_data['user_id'].isin(counts[counts >= 200].index)]
rating_data.rename(columns={'anime_id':'MAL_ID'}, inplace=True)

In [13]:
rating_data.shape

(41320341, 3)

In [72]:
anime_rating_data = anime_data_cleaned.merge(rating_data, on='MAL_ID', how='inner')

In [3]:
anime_rating_data.shape

(38541711, 12)

## User-based collaborative filtering - v2.0
- With sparse matrix to speed up the computation
- Clustering users by Kmeans

Split dataset into train and test

In [73]:
anime_ratings = anime_rating_data[['user_id', 'MAL_ID', 'rating']]

In [6]:
anime_ratings.shape

(26724793, 3)

### Split data into train and test

In [61]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets based on the users
train_data, test_data = train_test_split(rating_data, test_size=0.2, random_state=42)

In [62]:
from scipy.sparse import csr_matrix
user_item_matrix = train_data.pivot_table(index='user_id', columns='MAL_ID', values='rating').fillna(0)
train_data_sparse = csr_matrix(user_item_matrix.fillna(0).values)

In [100]:
user_item_matrix

MAL_ID     1    5    6    7    8   15   16   17   18   19  ...  47398  47402  \
user_id                                                    ...                 
3        9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  8.0  0.0  ...    0.0    0.0   
6        6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
16       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
17       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
19       8.0  6.0  8.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
353385   0.0  0.0  0.0  8.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
353386   7.0  0.0  8.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
353392   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
353395   0.0  8.0  9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
353398   0.0  0.0  0.0  0.0  0.0  7.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

MAL_ID   47403  47410  47614  47616  47618  48177  48456  cluster  
user_id                                                            
3          0.0    0.0    0.0    0.0    0.0    0.0    0.0        6  
6          0.0    0.0    0.0    0.0    0.0    0.0    0.0        5  
16         0.0    0.0    0.0    0.0    0.0    0.0    0.0        7  
17         0.0    0.0    0.0    0.0    0.0    0.0    0.0        9  
19         0.0    0.0    0.0    0.0    0.0    0.0    0.0        0  
...        ...    ...    ...    ...    ...    ...    ...      ...  
353385     0.0    0.0    0.0    0.0    0.0    0.0    0.0        5  
353386     0.0    0.0    0.0    0.0    0.0    0.0    0.0        6  
353392     0.0    0.0    0.0    0.0    0.0    0.0    0.0        1  
353395     0.0    0.0    0.0    0.0    0.0    0.0    0.0        2  
353398     0.0    0.0    0.0    0.0    0.0    0.0    0.0        9  

[95143 rows x 16848 columns]

In [98]:
train_data_sparse

<95143x16847 sparse matrix of type '<class 'numpy.float64'>'
	with 33056272 stored elements in Compressed Sparse Row format>

### Clustering users with KMeans

In [64]:
from sklearn.cluster import KMeans

# Cluster the users based on the sparse matrix
kmeans = KMeans(n_clusters=10, random_state=42).fit(train_data_sparse)

# Add the cluster labels to the user-item matrix
user_item_matrix['cluster'] = kmeans.labels_

### Predict ratings for the specific items that the user has rated in the test set

In [9]:
# pick random user_id from test_data
user_id = test_data['user_id'].sample(1).values[0]
user_id

114011

In [229]:
train_data_sparse.shape

(95143, 16847)

In [238]:
train_data_sparse[95138, :].shape

(1, 16847)

In [76]:
rating_data['MAL_ID'].nunique()

4684

In [122]:
from sklearn.metrics.pairwise import cosine_similarity
def predict_ratings_user_based(user_id):
    # Get the anime_ids that the user has actually rated
    anime_ids = test_data.loc[test_data['user_id'] == user_id]['MAL_ID'].values

    # for each anime_id, get the name of anime
    # names = []
    # for anime_id in anime_ids:
    #     name = anime_name.loc[anime_name['MAL_ID']==anime_id]['Name'].values[0]
    #     names.append(name)

    # Get the cluster of the user (e.g., 5)
    user_cluster = user_item_matrix['cluster'].loc[user_item_matrix['cluster'].index == user_id].values[0]
    
    # Get the users in the same cluster (e.g., [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    users_in_cluster = user_item_matrix[user_item_matrix['cluster'] == user_cluster].index
    
    # Get the ratings of the users in the same cluster
    ratings_of_users_in_cluster = train_data_sparse[user_item_matrix.index.isin(users_in_cluster)]
    
    row_index = user_item_matrix.index.get_loc(user_id)

    # Calculate the similarity between the user and the users in the same cluster
    similarity = cosine_similarity(train_data_sparse[row_index], ratings_of_users_in_cluster)
    print('-------similarity array------')
    print(similarity, similarity.shape)

    # Get the ratings for the specified anime_ids that exist in train_data_sparse
    # It is actually searching it from user_item_matrix but its fine because train_data_sparse is a csr_matrix made from user_item_matrix
    common_anime_ids = set(anime_ids).intersection(set(user_item_matrix.index.values))
    common_anime_ids = np.array(sorted(list(common_anime_ids)))
    
    common_anime_ids_idx  = [user_item_matrix.columns.get_loc(anime_id) for anime_id in common_anime_ids]
    
    # Use this in case if you want to get all the anime_ids from train_data_sparse
    anime_ids_idx  = [user_item_matrix.columns.get_loc(anime_id) for anime_id in anime_ids]

    # get index of users_in_cluster, common_anime_ids
    users_in_cluster_idx = [user_item_matrix.index.get_loc(user_id) for user_id in users_in_cluster]

    # Get the ratings for the specified anime_ids
    anime_ratings = np.asarray(train_data_sparse[users_in_cluster_idx, :][:, anime_ids_idx].todense())

    # Get the top-k similar users
    top_similar_users = np.argsort(similarity)[0][-1]
    print('-------top_similar_users------')
    print(users_in_cluster[top_similar_users])

    # Calculate the predicted ratings for the specified anime_ids
    predicted_ratings = anime_ratings.dot(similarity[0][top_similar_users]) / np.sum(np.abs(similarity[0][top_similar_users]))

    return predicted_ratings[0]


In [126]:
predicted_ratings = predict_ratings_user_based(user_id)
predicted_ratings, predicted_ratings.shape

-------similarity array------
[[0.27347739 0.32875137 0.20629679 ... 0.24250088 0.26552431 0.32655579]] (1, 5392)
-------top_similar_users------
114011


(array([ 0.,  0.,  9.,  0.,  0.,  0.,  0.,  8.,  0.,  8.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  1.,  6.,  6.,
         0.,  8.,  0.,  0.,  6.,  0.,  0.,  0., 10.,  8.,  0.,  0.,  0.,
        10.,  0.]),
 (41,))

In [125]:
actual_ratings = test_data.loc[test_data['user_id']==user_id]['rating'].values
actual_ratings, actual_ratings.shape

(array([ 7,  8,  8,  7,  8,  8,  7,  8,  8,  8,  9,  8,  7,  7,  9,  8,  7,
         9,  7,  7,  9,  8,  8,  8,  7, 10,  7,  8,  8,  7, 10,  8,  9,  8,
         8,  8, 10,  8,  9, 10,  8]),
 (41,))

In [16]:
def calculate_mae(predicted_ratings, actual_ratings):
    return np.mean(np.abs(predicted_ratings - actual_ratings))

In [127]:
calculate_mae(predicted_ratings, actual_ratings)

6.097560975609756

In [18]:
def calculate_rmse(predict_anime_ratings, actual_ratings):
    return np.sqrt(np.mean((predict_anime_ratings - actual_ratings)**2))

In [128]:
calculate_rmse(predicted_ratings, actual_ratings)

6.8645430452079035

### Predict ratings for top_k recommended items

In [185]:
train_data_sparse.shape

(95143, 16847)

In [175]:
def predict_ratings(user_id, k):
    # Get the cluster of the user
    # user_cluster = user_item_matrix.loc[user_id, 'cluster']
    user_cluster = user_item_matrix['cluster'].loc[user_item_matrix['cluster'].index == user_id].values[0]
    
    # Get the users in the same cluster
    users_in_cluster = user_item_matrix[user_item_matrix['cluster'] == user_cluster].index.intersection(train_data_sparse[:, 0].toarray().flatten().astype(int))
    
    # Get the ratings of the users in the same cluster
    ratings_of_users_in_cluster = train_data_sparse[users_in_cluster]
    
    # Calculate the similarity between the user and the users in the same cluster
    similarity = cosine_similarity(train_data_sparse[user_id], ratings_of_users_in_cluster)
    
    # Get the top-k similar users
    top_k_similar_users = np.argsort(similarity)[0][-k:]
    
    # Get the items rated by the top-k similar users
    items_rated_by_top_k_users = train_data_sparse[top_k_similar_users].toarray().T
    
    # Get the items not rated by the user
    unrated_items_by_user = np.isnan(user_item_matrix.loc[user_id])
    
    # Calculate the predicted rating for the unrated items
    predicted_ratings = items_rated_by_top_k_users.dot(similarity[0][top_k_similar_users]) / np.sum(similarity[0][top_k_similar_users])
    
    # Get the top-k recommended items
    top_k_items = np.argsort(predicted_ratings)[-k:]
    
    # Get the predicted ratings for the top-k items
    predicted_ratings_for_top_k_items = predicted_ratings[top_k_items]
    
    return top_k_items, predicted_ratings_for_top_k_items


In [181]:
# Top 10 recommendation and predicted ratings for user 6
top_k, predicted_ratings = predict_ratings(353385, k=10)
top_k, predicted_ratings

IndexError: row index (353385) out of range

### Evaluation

#### MAE@K

In [78]:
# Here is the problem, none of top_k animes are in the test_data
# So it doesn't work to calculate MAE by comparing train and test data
test_data.loc[test_data['user_id']==6].sort_values(by='MAL_ID', ascending=False)

user_id  MAL_ID  rating
739        6   13675       5
912        6   11691       7
759        6   11099       8
681        6   11073       6
766        6   10622       8
825        6   10497       9
677        6   10161       8
773        6   10067       8
785        6    9846       7
703        6    9756      10
865        6    9041       4
790        6    8800       8
886        6    8628       8
838        6    7337       8
875        6    7054       8
832        6    7024       4
809        6    6984       8
791        6    6973       8
692        6    6953       1
750        6    6607       3
817        6    6064       5
685        6    5529       6
934        6    5163       8
828        6    5041       7
683        6    4795       6
957        6    4548       7
910        6    4177       9
933        6    4158       7
899        6    3901       9
819        6    3652       9
676        6    3358       9
871        6    3092      10
915        6    2904       8
726        6    2897       6
954        6    2404       7
689        6    2201       5
670        6    1943      10
893        6    1890       6
686        6    1709       6
903        6    1686       7
974        6    1607       7
782        6    1554       6
666        6    1525       6
913        6    1496       5
849        6    1379       9
694        6    1117       6
928        6     908       6
947        6     874       6
741        6     849      10
972        6     689       8
735        6     659       8
720        6     597       8
755        6     523       7
935        6     514       6
925        6     121      10
798        6      65       7

#### MAP

In [11]:
def calculate_MAP_k(user_id, k=10):
    # Get the items in the test set for the user
    test_items = test_data.loc[user_id].dropna().index
    
    # Get the top-k recommended items
    top_k_items = get_top_k_recommendations(user_id, k)
    
    # Get the indices of the recommended items that are in the test set
    relevant_items = np.intersect1d(top_k_items, test_items, assume_unique=True)
    
    # Calculate the precision at k
    precision_at_k = len(relevant_items) / k
    
    return precision_at_k